[project]
name = "dwave-theme"
version = "0.1.0"
description = "A centralized theme and configuration package for D-Wave projects."
readme = "README.rst"
requires-python = ">=3.9"
dependencies = ["matplotlib>=3.10.6"]

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"
