[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dwave-theme"
dynamic = ["version"]
authors = [
    {name = "D-Wave", email = "tools@dwavesys.com"},
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
description = "A centralized theme and configuration package for D-Wave projects."
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.10"
dependencies = [
    "cycler>=0.12.1",
    "matplotlib>=3.10.6",
]

[dependency-groups]
test = [
    "pytest",
    "pytest-mock"
]

[tool.setuptools.dynamic]
version = {attr = "dwave.theme.__version__"}

[tool.setuptools.packages.find]
include = ["dwave.*"]

[tool.setuptools.package-data]
"*" = ["*.mplstyle"]

